name: fortumars_hrm_app
description: "FortuMars HRM Attendance Platform - A Flutter project with Firebase integration."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  google_fonts: ^6.1.0

  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0
  firebase_messaging: ^15.1.3

  # Camera and Image Processing
  camera: ^0.10.5+9
  image: ^4.1.7
  google_ml_kit: ^0.16.3

  # Location Services
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  # QR Code Scanning
  qr_code_scanner: ^1.0.1

  # Biometric Authentication
  local_auth: ^2.1.8

  # State Management
  provider: ^6.1.5

  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
