// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG-DMhpL-7SV3AVLBdEMFjYkt2SezuQ3s',
    appId: '1:836845512516:web:b12ebffd39778e27efd911',
    messagingSenderId: '836845512516',
    projectId: 'hrms-fortumars',
    authDomain: 'hrms-fortumars.firebaseapp.com',
    storageBucket: 'hrms-fortumars.firebasestorage.app',
    measurementId: 'G-XYMP114PXX',
  );

  // Web Firebase configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG-DMhpL-7SV3AVLBdEMFjYkt2SezuQ3s',
    appId: '1:836845512516:android:your-android-app-id',
    messagingSenderId: '836845512516',
    projectId: 'hrms-fortumars',
    storageBucket: 'hrms-fortumars.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG-DMhpL-7SV3AVLBdEMFjYkt2SezuQ3s',
    appId: '1:836845512516:ios:your-ios-app-id',
    messagingSenderId: '836845512516',
    projectId: 'hrms-fortumars',
    storageBucket: 'hrms-fortumars.firebasestorage.app',
    iosBundleId: 'com.fortumars.hrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG-DMhpL-7SV3AVLBdEMFjYkt2SezuQ3s',
    appId: '1:836845512516:ios:your-macos-app-id',
    messagingSenderId: '836845512516',
    projectId: 'hrms-fortumars',
    storageBucket: 'hrms-fortumars.firebasestorage.app',
    iosBundleId: 'com.fortumars.hrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG-DMhpL-7SV3AVLBdEMFjYkt2SezuQ3s',
    appId: '1:836845512516:web:b12ebffd39778e27efd911',
    messagingSenderId: '836845512516',
    projectId: 'hrms-fortumars',
    authDomain: 'hrms-fortumars.firebaseapp.com',
    storageBucket: 'hrms-fortumars.firebasestorage.app',
  );

}