// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCcuTsrEBmZNMwFLciZxbp5sbiJ1RWSvM',
    appId: '1:933599410604:web:8498099df5984366936209',
    messagingSenderId: '933599410604',
    projectId: 'myproject-f9e45',
    authDomain: 'myproject-f9e45.firebaseapp.com',
    storageBucket: 'myproject-f9e45.firebasestorage.app',
  );

  // Web Firebase configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD95UyPhJf4FpLbZL0kyisx5BnKj5zBPb8',
    appId: '1:933599410604:android:05eeb09398420971936209',
    messagingSenderId: '933599410604',
    projectId: 'myproject-f9e45',
    storageBucket: 'myproject-f9e45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzTK2andyeo0wbwaEMb9z6qfqQ70iMQms',
    appId: '1:933599410604:ios:afb84f521b0836b8936209',
    messagingSenderId: '933599410604',
    projectId: 'myproject-f9e45',
    storageBucket: 'myproject-f9e45.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzTK2andyeo0wbwaEMb9z6qfqQ70iMQms',
    appId: '1:933599410604:ios:afb84f521b0836b8936209',
    messagingSenderId: '933599410604',
    projectId: 'myproject-f9e45',
    storageBucket: 'myproject-f9e45.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCcuTsrEBmZNMwFLciZxbp5sbiJ1RWSvM',
    appId: '1:933599410604:web:03e831591a8da692936209',
    messagingSenderId: '933599410604',
    projectId: 'myproject-f9e45',
    authDomain: 'myproject-f9e45.firebaseapp.com',
    storageBucket: 'myproject-f9e45.firebasestorage.app',
  );

}